runtime: java11
env: standard
instance_class: B1
handlers:
  - url: .*
    script: auto
basic_scaling:
  max_instances: 10
  idle_timeout: 10m
service_account: smartfood-app-406605@appspot.gserviceaccount.com